export const PACIENTE_PROFESIONES_COMUNES = [
  'Abogado/a',
  'Administrativo/a',
  'Agrimensor/a',
  'Albanil',
  'Analista contable',
  'Analista de datos',
  'Analista de recursos humanos',
  'Analista financiero/a',
  'Arquitecto/a',
  'Asesor/a comercial',
  'Asistente administrativo/a',
  'Asistente social',
  'Auditor/a',
  'Auxiliar contable',
  'Auxiliar de farmacia',
  'Auxiliar de laboratorio',
  'Barbero/a',
  'Bioingeniero/a',
  'Bioquimico/a',
  'Cajero/a',
  'Camarero/a',
  'Carpintero/a',
  'Chofer',
  'Cobrador/a',
  'Cocinero/a',
  'Comerciante',
  'Community manager',
  'Contador/a',
  'Costurero/a',
  'Cuidador/a',
  'Dentista',
  'Desarrollador/a de software',
  'Disenador/a grafico/a',
  'Disenador/a industrial',
  'Docente',
  'Economista',
  'Electricista',
  'Enfermero/a',
  'Esteticista',
  'Farmaceutico/a',
  'Fisioterapeuta',
  'Fonoaudiologo/a',
  'Fotografo/a',
  'Gasista',
  'Herrero/a',
  'Ingeniero/a agronomo/a',
  'Ingeniero/a civil',
  'Ingeniero/a electronico/a',
  'Ingeniero/a en sistemas',
  'Ingeniero/a industrial',
  'Ingeniero/a mecanico/a',
  'Ingeniero/a quimico/a',
  'Instrumentador/a quirurgico/a',
  'Jardinero/a',
  'Jornalero/a',
  'Kinesiologo/a',
  'Laboratorista',
  'Licenciado/a en administracion',
  'Licenciado/a en marketing',
  'Logistico/a',
  'Maestro/a mayor de obras',
  'Maquinista',
  'Masajista',
  'Martillero/a publico/a',
  'Medico/a',
  'Medico/a veterinario/a',
  'Mecanico/a',
  'Nutricionista',
  'Odontologo/a',
  'Operador/a de call center',
  'Operario/a de fabrica',
  'Panadero/a',
  'Paramedico/a',
  'Peluquero/a',
  'Periodista',
  'Personal de limpieza',
  'Pintor/a',
  'Plomero/a',
  'Policia',
  'Productor/a de seguros',
  'Profesor/a de educacion fisica',
  'Programador/a',
  'Psicologo/a',
  'Psicopedagogo/a',
  'Publicista',
  'Recepcionista',
  'Repositor/a',
  'Secretaria/o',
  'Soldador/a',
  'Supervisor/a de ventas',
  'Tecnico/a de laboratorio',
  'Tecnico/a de mantenimiento',
  'Tecnico/a en electronica',
  'Tecnico/a en radiologia',
  'Terapista ocupacional',
  'Tesorero/a',
  'Traductor/a',
  'Trabajador/a social',
  'Vendedor/a',
  'Visitador/a medico/a',
] as const;
